package com.emerson.bpm.dsl;
/**
 * Class generated by the take compiler. 
 * This class holds the constants referenced in the knowledge base. 
 * @version Thu Jun 17 16:48:16 IST 2021
 */
@SuppressWarnings("unchecked")
public class Constants{
public static int x;
public static int y;
}
