package com.emerson.bpm.dsl;

/**
 * Class generated by the take compiler.
 * This class represents the predicate greater_than
 * @version Wed Jun 16 13:25:12 IST 2021
 */
public class greater_than {
    public double slot1;
    public double slot2;

    public greater_than(double slot1, double slot2) {
        super();
        this.slot1 = slot1;
        this.slot2 = slot2;
    }

    public greater_than() {
        super();
    }
}
