package com.emerson.bpm.dsl;

/**
 * Class generated by the take compiler.
 * This class represents the predicate whichIsGreater
 * @version Wed Jun 16 13:48:42 IST 2021
 */
public class whichIsGreater {
    public long slot1;
    public long slot2;
    public long slot3;

    public whichIsGreater(long slot1, long slot2, long slot3) {
        super();
        this.slot1 = slot1;
        this.slot2 = slot2;
        this.slot3 = slot3;
    }

    public whichIsGreater() {
        super();
    }
}
