package com.emerson.bpm.dsl;
/**
 * Class generated by the take compiler. 
 * This class holds the constants referenced in the knowledge base. 
 * @version Wed Jun 16 13:15:35 IST 2021
 */
@SuppressWarnings("unchecked")
public class Constants{
public static int x;
public static int y;
}
