package com.emerson.bpm.dsl;

import com.emerson.bpm.dsl.*;

import nz.org.take.rt.*;


/**
 * Class generated by the take compiler.
 * @version Wed Jun 16 13:15:35 IST 2021
 */
@SuppressWarnings("unchecked")
public class KBImpl implements com.emerson.bpm.dsl.RuleClientTest$whichIsGreater {
    private static java.util.Map<String, java.util.Map<String, String>> _annotations =
        null;

    /**
    * Method that can be used to query annotations at runtime.
    * @param id the id of the rule (or other knowledge element)
    * @return a map of annotations (string-string mappings)
    * code generated using velocity template LocalAnnotationMethod.vm
    */
    public java.util.Map<String, String> getAnnotations(String id) {
        if (_annotations == null) {
            synchronized (KBImpl.class) {
                if (_annotations == null) {
                    java.beans.XMLDecoder decoder = new java.beans.XMLDecoder(new java.io.BufferedInputStream(
                                KBImpl.class.getResourceAsStream(
                                    "/com/emerson/bpm/dsl/annotations.xml")));
                    _annotations = (java.util.Map<String, java.util.Map<String, String>>) decoder.readObject();
                    decoder.close();
                }
            }
        }

        return _annotations.get(id);
    }

    /**
     * Method that can be used to query global annotations at runtime.
     * Global annotations are attached to the knowledge base, not to
     * a particular element (rule,..).
     * @return a map of annotations (string-string mappings)
     * code generated using velocity template GlobalAnnotationMethod.vm
    */
    public java.util.Map<String, String> getAnnotations() {
        return getAnnotations("___global_annotations");
    }

    /**
    * Method generated for query whichIsGreater[in,in,out]
    * @param slot1 input parameter generated from slot 0
    * @param slot2 input parameter generated from slot 1
    * @return an iterator for instances of whichIsGreater
    */
    public ResultSet<whichIsGreater> whichIsGreater_110(final long slot1,
        final long slot2) {
        DerivationController _derivation = new DefaultDerivationController();
        ResultSet<whichIsGreater> _result = new ResultSet(KBFragement_whichIsGreater_110.whichIsGreater_110(
                    slot1, slot2, _derivation), _derivation);

        return _result;
    }
}
