//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.30 at 01:32:48 PM IST 
//


package com.emerson.bpm.dsl.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ComparatorType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ComparatorType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;choice&gt;
 *         &lt;element name="EQUALS" type="{http://www.example.org/RulkesDSLSchema}EqualsComparisonType"/&gt;
 *         &lt;element name="GT" type="{http://www.example.org/RulkesDSLSchema}GreaterThanComparisonType"/&gt;
 *         &lt;element name="LT" type="{http://www.example.org/RulkesDSLSchema}LessThanComparisonType"/&gt;
 *         &lt;element name="GTE" type="{http://www.example.org/RulkesDSLSchema}GreaterThanEqualsComparisonType"/&gt;
 *         &lt;element name="LTE" type="{http://www.example.org/RulkesDSLSchema}LessThanEqualsComparisonType"/&gt;
 *         &lt;element name="NEQ" type="{http://www.example.org/RulkesDSLSchema}NotEqualsComparisonType"/&gt;
 *         &lt;element name="DNX" type="{http://www.example.org/RulkesDSLSchema}NotExistsComparisonType"/&gt;
 *         &lt;element name="TEQ" type="{http://www.example.org/RulkesDSLSchema}MatchesComparisonType"/&gt;
 *       &lt;/choice&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ComparatorType", propOrder = {
    "equals",
    "gt",
    "lt",
    "gte",
    "lte",
    "neq",
    "dnx",
    "teq"
})
@XmlSeeAlso({
    NameComparatorType.class
})
public class ComparatorType {

    @XmlElement(name = "EQUALS")
    protected EqualsComparisonType equals;
    @XmlElement(name = "GT")
    protected GreaterThanComparisonType gt;
    @XmlElement(name = "LT")
    protected LessThanComparisonType lt;
    @XmlElement(name = "GTE")
    protected GreaterThanEqualsComparisonType gte;
    @XmlElement(name = "LTE")
    protected LessThanEqualsComparisonType lte;
    @XmlElement(name = "NEQ")
    protected NotEqualsComparisonType neq;
    @XmlElement(name = "DNX")
    protected NotExistsComparisonType dnx;
    @XmlElement(name = "TEQ")
    protected MatchesComparisonType teq;

    /**
     * Gets the value of the equals property.
     * 
     * @return
     *     possible object is
     *     {@link EqualsComparisonType }
     *     
     */
    public EqualsComparisonType getEQUALS() {
        return equals;
    }

    /**
     * Sets the value of the equals property.
     * 
     * @param value
     *     allowed object is
     *     {@link EqualsComparisonType }
     *     
     */
    public void setEQUALS(EqualsComparisonType value) {
        this.equals = value;
    }

    /**
     * Gets the value of the gt property.
     * 
     * @return
     *     possible object is
     *     {@link GreaterThanComparisonType }
     *     
     */
    public GreaterThanComparisonType getGT() {
        return gt;
    }

    /**
     * Sets the value of the gt property.
     * 
     * @param value
     *     allowed object is
     *     {@link GreaterThanComparisonType }
     *     
     */
    public void setGT(GreaterThanComparisonType value) {
        this.gt = value;
    }

    /**
     * Gets the value of the lt property.
     * 
     * @return
     *     possible object is
     *     {@link LessThanComparisonType }
     *     
     */
    public LessThanComparisonType getLT() {
        return lt;
    }

    /**
     * Sets the value of the lt property.
     * 
     * @param value
     *     allowed object is
     *     {@link LessThanComparisonType }
     *     
     */
    public void setLT(LessThanComparisonType value) {
        this.lt = value;
    }

    /**
     * Gets the value of the gte property.
     * 
     * @return
     *     possible object is
     *     {@link GreaterThanEqualsComparisonType }
     *     
     */
    public GreaterThanEqualsComparisonType getGTE() {
        return gte;
    }

    /**
     * Sets the value of the gte property.
     * 
     * @param value
     *     allowed object is
     *     {@link GreaterThanEqualsComparisonType }
     *     
     */
    public void setGTE(GreaterThanEqualsComparisonType value) {
        this.gte = value;
    }

    /**
     * Gets the value of the lte property.
     * 
     * @return
     *     possible object is
     *     {@link LessThanEqualsComparisonType }
     *     
     */
    public LessThanEqualsComparisonType getLTE() {
        return lte;
    }

    /**
     * Sets the value of the lte property.
     * 
     * @param value
     *     allowed object is
     *     {@link LessThanEqualsComparisonType }
     *     
     */
    public void setLTE(LessThanEqualsComparisonType value) {
        this.lte = value;
    }

    /**
     * Gets the value of the neq property.
     * 
     * @return
     *     possible object is
     *     {@link NotEqualsComparisonType }
     *     
     */
    public NotEqualsComparisonType getNEQ() {
        return neq;
    }

    /**
     * Sets the value of the neq property.
     * 
     * @param value
     *     allowed object is
     *     {@link NotEqualsComparisonType }
     *     
     */
    public void setNEQ(NotEqualsComparisonType value) {
        this.neq = value;
    }

    /**
     * Gets the value of the dnx property.
     * 
     * @return
     *     possible object is
     *     {@link NotExistsComparisonType }
     *     
     */
    public NotExistsComparisonType getDNX() {
        return dnx;
    }

    /**
     * Sets the value of the dnx property.
     * 
     * @param value
     *     allowed object is
     *     {@link NotExistsComparisonType }
     *     
     */
    public void setDNX(NotExistsComparisonType value) {
        this.dnx = value;
    }

    /**
     * Gets the value of the teq property.
     * 
     * @return
     *     possible object is
     *     {@link MatchesComparisonType }
     *     
     */
    public MatchesComparisonType getTEQ() {
        return teq;
    }

    /**
     * Sets the value of the teq property.
     * 
     * @param value
     *     allowed object is
     *     {@link MatchesComparisonType }
     *     
     */
    public void setTEQ(MatchesComparisonType value) {
        this.teq = value;
    }

}
