//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.30 at 01:32:48 PM IST 
//


package com.emerson.bpm.dsl.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for FieldComparisonType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FieldComparisonType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;choice&gt;
 *         &lt;element name="fieldjoin" type="{http://www.example.org/RulkesDSLSchema}NameComparatorType"/&gt;
 *         &lt;element name="fieldvalue" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/choice&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FieldComparisonType", propOrder = {
    "fieldjoin",
    "fieldvalue"
})
public class FieldComparisonType {

    protected NameComparatorType fieldjoin;
    protected String fieldvalue;

    /**
     * Gets the value of the fieldjoin property.
     * 
     * @return
     *     possible object is
     *     {@link NameComparatorType }
     *     
     */
    public NameComparatorType getFieldjoin() {
        return fieldjoin;
    }

    /**
     * Sets the value of the fieldjoin property.
     * 
     * @param value
     *     allowed object is
     *     {@link NameComparatorType }
     *     
     */
    public void setFieldjoin(NameComparatorType value) {
        this.fieldjoin = value;
    }

    /**
     * Gets the value of the fieldvalue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFieldvalue() {
        return fieldvalue;
    }

    /**
     * Sets the value of the fieldvalue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFieldvalue(String value) {
        this.fieldvalue = value;
    }

}
