//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.30 at 01:32:48 PM IST 
//


package com.emerson.bpm.dsl.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for JoinComparatorType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="JoinComparatorType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.example.org/RulkesDSLSchema}NameComparatorType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="whereElement" type="{http://www.example.org/RulkesDSLSchema}ValuesComparatorType"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "JoinComparatorType", propOrder = {
    "whereElement"
})
@XmlSeeAlso({
    NotExistsComparisonType.class
})
public class JoinComparatorType
    extends NameComparatorType
{

    @XmlElement(required = true)
    protected ValuesComparatorType whereElement;

    /**
     * Gets the value of the whereElement property.
     * 
     * @return
     *     possible object is
     *     {@link ValuesComparatorType }
     *     
     */
    public ValuesComparatorType getWhereElement() {
        return whereElement;
    }

    /**
     * Sets the value of the whereElement property.
     * 
     * @param value
     *     allowed object is
     *     {@link ValuesComparatorType }
     *     
     */
    public void setWhereElement(ValuesComparatorType value) {
        this.whereElement = value;
    }

}
