//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.30 at 01:32:48 PM IST 
//


package com.emerson.bpm.dsl.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for NameComparatorType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="NameComparatorType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.example.org/RulkesDSLSchema}ComparatorType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="firstField" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="otherField" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NameComparatorType", propOrder = {
    "firstField",
    "otherField"
})
@XmlSeeAlso({
    JoinComparatorType.class
})
public class NameComparatorType
    extends ComparatorType
{

    @XmlElement(required = true)
    protected String firstField;
    @XmlElement(required = true)
    protected String otherField;

    /**
     * Gets the value of the firstField property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFirstField() {
        return firstField;
    }

    /**
     * Sets the value of the firstField property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFirstField(String value) {
        this.firstField = value;
    }

    /**
     * Gets the value of the otherField property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOtherField() {
        return otherField;
    }

    /**
     * Sets the value of the otherField property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOtherField(String value) {
        this.otherField = value;
    }

}
