//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.30 at 01:32:48 PM IST 
//


package com.emerson.bpm.dsl.schema;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.monarch.v2.react.dsl.schema package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Network_QNAME = new QName("http://www.example.org/RulkesDSLSchema", "network");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.monarch.v2.react.dsl.schema
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link RootNodeType }
     * 
     */
    public RootNodeType createRootNodeType() {
        return new RootNodeType();
    }

    /**
     * Create an instance of {@link ObjectNodeType }
     * 
     */
    public ObjectNodeType createObjectNodeType() {
        return new ObjectNodeType();
    }

    /**
     * Create an instance of {@link AlphaNodeType }
     * 
     */
    public AlphaNodeType createAlphaNodeType() {
        return new AlphaNodeType();
    }

    /**
     * Create an instance of {@link ComparatorType }
     * 
     */
    public ComparatorType createComparatorType() {
        return new ComparatorType();
    }

    /**
     * Create an instance of {@link NameComparatorType }
     * 
     */
    public NameComparatorType createNameComparatorType() {
        return new NameComparatorType();
    }

    /**
     * Create an instance of {@link JoinComparatorType }
     * 
     */
    public JoinComparatorType createJoinComparatorType() {
        return new JoinComparatorType();
    }

    /**
     * Create an instance of {@link ComparisonType }
     * 
     */
    public ComparisonType createComparisonType() {
        return new ComparisonType();
    }

    /**
     * Create an instance of {@link EqualsComparisonType }
     * 
     */
    public EqualsComparisonType createEqualsComparisonType() {
        return new EqualsComparisonType();
    }

    /**
     * Create an instance of {@link GreaterThanComparisonType }
     * 
     */
    public GreaterThanComparisonType createGreaterThanComparisonType() {
        return new GreaterThanComparisonType();
    }

    /**
     * Create an instance of {@link LessThanComparisonType }
     * 
     */
    public LessThanComparisonType createLessThanComparisonType() {
        return new LessThanComparisonType();
    }

    /**
     * Create an instance of {@link GreaterThanEqualsComparisonType }
     * 
     */
    public GreaterThanEqualsComparisonType createGreaterThanEqualsComparisonType() {
        return new GreaterThanEqualsComparisonType();
    }

    /**
     * Create an instance of {@link LessThanEqualsComparisonType }
     * 
     */
    public LessThanEqualsComparisonType createLessThanEqualsComparisonType() {
        return new LessThanEqualsComparisonType();
    }

    /**
     * Create an instance of {@link NotEqualsComparisonType }
     * 
     */
    public NotEqualsComparisonType createNotEqualsComparisonType() {
        return new NotEqualsComparisonType();
    }

    /**
     * Create an instance of {@link NotExistsComparisonType }
     * 
     */
    public NotExistsComparisonType createNotExistsComparisonType() {
        return new NotExistsComparisonType();
    }

    /**
     * Create an instance of {@link MatchesComparisonType }
     * 
     */
    public MatchesComparisonType createMatchesComparisonType() {
        return new MatchesComparisonType();
    }

    /**
     * Create an instance of {@link FieldComparisonType }
     * 
     */
    public FieldComparisonType createFieldComparisonType() {
        return new FieldComparisonType();
    }

    /**
     * Create an instance of {@link ValueComparatorType }
     * 
     */
    public ValueComparatorType createValueComparatorType() {
        return new ValueComparatorType();
    }

    /**
     * Create an instance of {@link ValuesComparatorType }
     * 
     */
    public ValuesComparatorType createValuesComparatorType() {
        return new ValuesComparatorType();
    }

    /**
     * Create an instance of {@link RTMNodeType }
     * 
     */
    public RTMNodeType createRTMNodeType() {
        return new RTMNodeType();
    }

    /**
     * Create an instance of {@link JoinNodeType }
     * 
     */
    public JoinNodeType createJoinNodeType() {
        return new JoinNodeType();
    }

    /**
     * Create an instance of {@link ContextType }
     * 
     */
    public ContextType createContextType() {
        return new ContextType();
    }

    /**
     * Create an instance of {@link RulesIDContextType }
     * 
     */
    public RulesIDContextType createRulesIDContextType() {
        return new RulesIDContextType();
    }

    /**
     * Create an instance of {@link RuleComplexType }
     * 
     */
    public RuleComplexType createRuleComplexType() {
        return new RuleComplexType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RootNodeType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link RootNodeType }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.example.org/RulkesDSLSchema", name = "network")
    public JAXBElement<RootNodeType> createNetwork(RootNodeType value) {
        return new JAXBElement<RootNodeType>(_Network_QNAME, RootNodeType.class, null, value);
    }

}
