//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.30 at 01:32:48 PM IST 
//


package com.emerson.bpm.dsl.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ObjectNodeType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ObjectNodeType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ruleContext" type="{http://www.example.org/RulkesDSLSchema}RulesIDContextType"/&gt;
 *         &lt;element name="className" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="alphaNodes" type="{http://www.example.org/RulkesDSLSchema}AlphaNodeType"/&gt;
 *         &lt;element name="data" type="{http://www.w3.org/2001/XMLSchema}base64Binary"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ObjectNodeType", propOrder = {
    "ruleContext",
    "className",
    "alphaNodes",
    "data"
})
public class ObjectNodeType {

    @XmlElement(required = true)
    protected RulesIDContextType ruleContext;
    @XmlElement(required = true)
    protected String className;
    @XmlElement(required = true)
    protected AlphaNodeType alphaNodes;
    @XmlElement(required = true)
    protected byte[] data;

    /**
     * Gets the value of the ruleContext property.
     * 
     * @return
     *     possible object is
     *     {@link RulesIDContextType }
     *     
     */
    public RulesIDContextType getRuleContext() {
        return ruleContext;
    }

    /**
     * Sets the value of the ruleContext property.
     * 
     * @param value
     *     allowed object is
     *     {@link RulesIDContextType }
     *     
     */
    public void setRuleContext(RulesIDContextType value) {
        this.ruleContext = value;
    }

    /**
     * Gets the value of the className property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClassName() {
        return className;
    }

    /**
     * Sets the value of the className property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClassName(String value) {
        this.className = value;
    }

    /**
     * Gets the value of the alphaNodes property.
     * 
     * @return
     *     possible object is
     *     {@link AlphaNodeType }
     *     
     */
    public AlphaNodeType getAlphaNodes() {
        return alphaNodes;
    }

    /**
     * Sets the value of the alphaNodes property.
     * 
     * @param value
     *     allowed object is
     *     {@link AlphaNodeType }
     *     
     */
    public void setAlphaNodes(AlphaNodeType value) {
        this.alphaNodes = value;
    }

    /**
     * Gets the value of the data property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getData() {
        return data;
    }

    /**
     * Sets the value of the data property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setData(byte[] value) {
        this.data = value;
    }

}
